version: '3'

services:
  ocsapplication:
    image: ocsinventory/ocsinventory-docker-image:2.12.3
    container_name: ocsinventory-server
    restart: always
    ports:
      - 28886:80
    volumes:
      - /volume1/docker/ocsinventory/app/perlcom:/etc/ocsinventory-server
      - /volume1/docker/ocsinventory/app/reports-extensions:/usr/share/ocsinventory-reports/ocsreports/extensions
      - /volume1/docker/ocsinventory/app/varlib:/var/lib/ocsinventory-reports
      - /volume1/docker/ocsinventory/app/httpdconf:/etc/apache2/conf-available
      - /volume1/docker/ocsinventory/app/profiles:/usr/share/ocsinventory-reports/ocsreports/config/profiles
    environment:
      OCS_DB_SERVER: ocsinventory-db
      OCS_DB_USER: ocsuser
      OCS_DB_PASS: ocspass
      OCS_DB_NAME: ocsweb
      OCS_SSL_ENABLED: 0
      OCS_DBI_PRINT_ERROR: 0
      AUTH_TYPE: 1
    networks:
      - localocs
    depends_on:
      - ocsdb

  ocsdb:
    image: mysql:8.0
    container_name: ocsinventory-db
    restart: always
    volumes:
      - /volume1/docker/ocsinventory/sql:/docker-entrypoint-initdb.d
      - /volume1/docker/ocsinventory/mydb:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_USER: ocsuser
      MYSQL_PASSWORD: ocspass
      MYSQL_DATABASE: ocsweb
    networks:
      - localocs

networks:
  localocs:
