version: '3'

services:
  ocsapplication:
    image: ocsinventory/ocsinventory-docker-image:2.12.3
    container_name : ocsinventory-server
    restart: always
    ports:
      - 28890:80
    expose:
      - "80"
    volumes:
      - /volume1/docker/ocsinventory/apache/perlcomdata:/etc/ocsinventory-server
      - /volume1/docker/ocsinventory/apache/ocsreportsdata:/usr/share/ocsinventory-reports/ocsreports/extensions
      - /volume1/docker/ocsinventory/apache/varlibdata:/var/lib/ocsinventory-reports
      - /volume1/docker/ocsinventory/apache/httpdconfdata:/etc/apache2/conf-available
      - /volume1/docker/ocsinventory/apache/profilesconfdata:/usr/share/ocsinventory-reports/ocsreports/config/profiles
      - /volume1/docker/ocsinventory/apache/ocsreports:/usr/share/ocsinventory-reports/ocsreports
    environment:
      OCS_DB_SERVER: ocsinventory-db
      OCS_DB_USER: ocsuser
      OCS_DB_PASS: ocspass
      OCS_DB_NAME: ocsweb
      # See documentation to set up SSL for MySQL
      OCS_SSL_ENABLED: 0
      OCS_DBI_PRINT_ERROR: 0
      # Define the auth type :
      # 1 : Local Only
      # 2 : Local and LDAP
      # 3 : LDAP Only
      # 4 : LDAP with SSO
      # 5 : Always OK, won't ask for user and password
      # 6 : CAS authentication
      AUTH_TYPE: 1
    links:
      - ocsdb
    networks:
      - localocs
    depends_on:
      - ocsdb    

  ocsdb :
    image: mariadb:10.11
    # image : mysql:8.0
    container_name : ocsinventory-db
    restart: always
    ports:
      - 23306:3306
    expose :
      - "3306"
    volumes :
      - /volume1/docker/ocsinventory/sql/:/docker-entrypoint-initdb.d/
      - /volume1/docker/ocsinventory/sqldata:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD : rootpass
      MYSQL_USER : ocsuser
      MYSQL_PASSWORD : ocspass
      MYSQL_DATABASE : ocsweb
    networks:
      - localocs

networks:
  localocs:
